version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce:2.11.1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - webpress

volumes:
  portainer:
