version: '3.8'
services:
  nginx:
    build:
      context: images/nginx
    restart: always
    networks:
      - webpress
    environment:
      - NGINX_PORT=8080
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
    labels:
      vn.webpress.name: 'nginx'
  php:
    build:
      context: images/php/8.1/alpine/fpm
    restart: always
    labels:
      vn.webpress.name: 'php'
    networks:
      - webpress
  database:
    image: '${MYSQL_IMAGE:-mysql:8.0}'
    restart: always
    command: --default-authentication-plugin=mysql_native_password --disable-log-bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=konga
      - MYSQL_USER=konga
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    networks:
      - webpress
  kong-migrations:
    build:
      context: images/kong
    restart: on-failure
    command: kong migrations bootstrap
    depends_on:
      - kongdb
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: ${KONG_PG_DATABASE_HOST:-kongdb}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: 'kongpwd'
    networks:
      - webpress

  kong-migrations-up:
    build:
      context: images/kong
    restart: on-failure
    command: kong migrations up && kong migrations finish
    depends_on:
      - kongdb
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: ${KONG_PG_DATABASE_HOST:-kongdb}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: 'kongpwd'
    networks:
      - webpress

  kong:
    build:
      context: images/kong
    restart: always
    ports:
      - '80:8000/tcp'
      - '443:8443/tcp'
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: ${KONG_PG_DATABASE_HOST:-kongdb}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: 'kongpwd'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: /etc/ssl/certs/ca-certificates.crt
    depends_on:
      - kongdb
    networks:
      - webpress

  kongdb:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD: 'kongpwd'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${KONG_PG_USER:-kong}']
      interval: 30s
      timeout: 30s
      retries: 3
    stdin_open: true
    tty: true
    volumes:
      - kongdb:/var/lib/postgresql/data
    networks:
      - webpress
  konga:
    image: pantsel/konga
    restart: always
    links:
      - kong
    environment:
      TOKEN_SECRET: AgzCkxCFNAsrXys8Q5gbfDSH
      KONGA_HOOK_TIMEOUT: 10000
      DB_ADAPTER: mysql
      DB_HOST: database
      DB_USER: konga
      DB_DATABASE: konga
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '30004:1337'
    networks:
      - webpress

volumes:
  kongdb:
    external: true

  dbdata:
    external: true

networks:
  webpress:
    external: true
