version: '3.8'
services:
  agent:
    image: '${AGENT_IMAGE:-webpress/agent}'
    restart: always
    environment:
      - 'DB_HOST=database'
      - 'DB_PORT=3306'
      - 'DB_NAME=mysql'
      - 'DB_USER=root'
      - 'DB_PASS=${DB_ROOT_PASSWORD}'
    volumes:
      - /var/www/web:/var/www/web
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '${AGENT_PUBLIC_PORT:-30001}:3000/tcp'
    networks:
      - webpress
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
